### ISSUE TITLE
Flakky tests

### ISSUE THREAD

**Issue by piorek** [twosigma/beakerx_kernel_scala#8]
When running install scripts from https://github.com/twosigma/beakerx_tests/blob/master/dev_scripts/install_kernels_notebook.sh

To be more precise:
```
(cd ../../beakerx_kernel_scala/scala-dist; pip install -r requirements.txt --verbose; beakerx_kernel_scala install)
```

More than once I had failing tests:

```
51 tests completed, 2 failed
    > Task :sparkex:test FAILED
    > Task :sparkex:copyDependencies
    FAILURE: Build failed with an exception.
    * What went wrong:
    Execution failed for task ':sparkex:test'.
    > There were failing tests. See the report at: file:///home/lukasz/code/codete/beakerx_kernel_scala/sparkex/build/reports/tests/test/index.html
    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
    * Get more help at https://help.gradle.org
    Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
    Use '--warning-mode all' to show the individual deprecation warnings.
    See https://docs.gradle.org/6.4.1/userguide/command_line_interface.html#sec:command_line_warnings
    BUILD FAILED in 1m 39s
    23 actionable tasks: 10 executed, 13 up-to-date
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/lukasz/code/codete/beakerx_kernel_scala/scala-dist/setup.py", line 85, in <module>
        setup(**setup_args)
      File "/home/lukasz/miniconda3/envs/beakerx/lib/python3.7/site-packages/setuptools/__init__.py", line 163, in setup
        return distutils.core.setup(**attrs)
      File "/home/lukasz/miniconda3/envs/beakerx/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/lukasz/miniconda3/envs/beakerx/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/lukasz/miniconda3/envs/beakerx/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/lukasz/code/codete/beakerx_kernel_scala/scala-dist/setupbase.py", line 164, in run
        [self.run_command(cmd) for cmd in cmds]
      File "/home/lukasz/code/codete/beakerx_kernel_scala/scala-dist/setupbase.py", line 164, in <listcomp>
        [self.run_command(cmd) for cmd in cmds]
      File "/home/lukasz/miniconda3/envs/beakerx/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/lukasz/miniconda3/envs/beakerx/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/lukasz/code/codete/beakerx_kernel_scala/scala-dist/setupbase.py", line 135, in run
        self.skip_test_option(skip_tests)], cwd=path)
      File "/home/lukasz/code/codete/beakerx_kernel_scala/scala-dist/setupbase.py", line 147, in run
        return check_call(cmd, *args, **kwargs)
      File "/home/lukasz/miniconda3/envs/beakerx/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['./gradlew', '--no-daemon', 'install', '-Dskip.tests=False']' returned non-zero exit status 1.
  Rolling back uninstall of beakerx-kernel-scala
  Moving to /home/lukasz/miniconda3/envs/beakerx/bin/beakerx_kernel_scala
   from /tmp/pip-uninstall-0tonykz1/beakerx_kernel_scala
  Moving to /home/lukasz/miniconda3/envs/beakerx/lib/python3.7/site-packages/beakerx-kernel-scala.egg-link
   from /tmp/pip-uninstall-im4cu27o/beakerx-kernel-scala.egg-link
  Replacing /home/lukasz/miniconda3/envs/beakerx/bin/beakerx_kernel_scala from /tmp/pip-uninstall-0tonykz1/beakerx_kernel_scala
  Replacing /home/lukasz/miniconda3/envs/beakerx/lib/python3.7/site-packages/beakerx-kernel-scala.egg-link from /tmp/pip-uninstall-im4cu27o/beakerx-kernel-scala.egg-link
  Rolling /home/lukasz/miniconda3/envs/beakerx/lib/python3.7/site-packages/easy-install.pth back to previous state
ERROR: Command errored out with exit status 1: /home/lukasz/miniconda3/envs/beakerx/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/lukasz/code/codete/beakerx_kernel_scala/scala-dist/setup.py'"'"'; __file__='"'"'/home/lukasz/code/codete/beakerx_kernel_scala/scala-dist/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/home/lukasz/miniconda3/envs/beakerx/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 216, in _main
    status = self.run(options, args)
  File "/home/lukasz/miniconda3/envs/beakerx/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/home/lukasz/miniconda3/envs/beakerx/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 421, in run
    pycompile=options.compile,
  File "/home/lukasz/miniconda3/envs/beakerx/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 90, in install_given_reqs
    pycompile=pycompile,
  File "/home/lukasz/miniconda3/envs/beakerx/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 799, in install
    unpacked_source_directory=self.unpacked_source_directory,
  File "/home/lukasz/miniconda3/envs/beakerx/lib/python3.7/site-packages/pip/_internal/operations/install/editable_legacy.py", line 51, in install_editable
    cwd=unpacked_source_directory,
  File "/home/lukasz/miniconda3/envs/beakerx/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /home/lukasz/miniconda3/envs/beakerx/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/lukasz/code/codete/beakerx_kernel_scala/scala-dist/setup.py'"'"'; __file__='"'"'/home/lukasz/code/codete/beakerx_kernel_scala/scala-dist/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
Removed build tracker: '/tmp/pip-req-tracker-jblhyla0'
Traceback (most recent call last):
  File "/home/lukasz/miniconda3/envs/beakerx/bin/beakerx_kernel_scala", line 33, in <module>
    sys.exit(load_entry_point('beakerx-kernel-scala', 'console_scripts', 'beakerx_kernel_scala')())
  File "/home/lukasz/miniconda3/envs/beakerx/bin/beakerx_kernel_scala", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/home/lukasz/miniconda3/envs/beakerx/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 558, in distribution
    return Distribution.from_name(distribution_name)
  File "/home/lukasz/miniconda3/envs/beakerx/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 215, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for beakerx-kernel-scala```

**Comment by jaroslawmalekcodete** [comment]
Hi @piorek 
could you try to reproduce this problem again and provide more details from 
_**See the report at: file:///home/lukasz/code/codete/beakerx_kernel_scala/sparkex/build/reports/tests/test/index.html**_ ?
